name = "clipboard-sync-relay"
main = "src/index.ts"
compatibility_date = "2024-10-22"

# Durable Objects binding
[[durable_objects.bindings]]
name = "CLIPBOARD_SESSION"
class_name = "ClipboardSession"
script_name = "clipboard-sync-relay"

# Durable Objects migration
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ClipboardSession"]
